export const portfolioData = [
  {
    id: 1,
    title: "World Ports and Trade",
    category: "Website Design and Development",
    image: "images/portfolio/web3.png",
    link: "portfolio_details",
  },
  {
    id: 2,
    title: "Bytravel World",
    category: "Website Development",
    image: "images/portfolio/web5.png",
    link: "portfolio_details",
  },
  {
    id: 3,
    title: "Astro Shraddha",
    category: "Website Development",
    image: "images/portfolio/web8.png",
    link: "portfolio_details",
  },
  {
    id: 4,
    title: "VH Club",
    category: "Website Design / Logo Design",
    image: "images/portfolio/logo1.jpg",
    link: "portfolio_details",
  },
  {
    id: 5,
    title: "BVM Hospital",
    category: "Website Design / Logo Design",
    image: "images/portfolio/logo2.jpg",
    link: "portfolio_details",
  },
  {
    id: 6,
    title: "CIOU",
    category: "Logo Design",
    image: "images/portfolio/logo3.jpg",
    link: "portfolio_details",
  },
  {
    id: 7,
    title: "Insurance Guru",
    category: "Logo Design",
    image: "images/portfolio/logo4.jpg",
    link: "portfolio_details",
  },
  {
    id: 8,
    title: "ASMI",
    category: "Logo Design",
    image: "images/portfolio/logo5.jpg",
    link: "portfolio_details",
  },
  {
    id: 9,
    title: "BVM Hospital",
    category: "Website Development",
    image: "images/portfolio/web1.jpg",
    link: "portfolio_details",
  },
  {
    id: 10,
    title: "Box cricket",
    category: "UI/UX Design / Website Development",
    image: "images/portfolio/web2.png",
    link: "portfolio_details",
  },
];
